### ISSUE TITLE
是否适用于multi-shot

### ISSUE THREAD

**Issue by zhengshuo1** [songwsx/person_search_demo#2]
您好！
       有个问题请教一下。您展示的结果，“白衣服女生在C楼前走过”，以及“白帽子男生在校门前走过",这两个例子处理的都是同一摄像头在相近的时间内拍下的帧对吧？如果是非同一摄像头拍下的帧，用这个模型处理，是不是就效果不佳了？

**Comment by songwsx** [comment]
可以啊，这就是reID要做的
