### ISSUE TITLE
查询自己的数据

### ISSUE THREAD

**Issue by EtheneXiang** [songwsx/person_search_demo#5]
我data/samples里面放的自己的视频帧
![image](https://user-images.githubusercontent.com/49241737/69596612-226ff200-103e-11ea-9980-bd05c19c9ece.png)
query里面放的截取出来的人体
![image](https://user-images.githubusercontent.com/49241737/69596632-33b8fe80-103e-11ea-89c3-58d961ac0d93.png)
然后我运行程序python3 search.py报错
![image](https://user-images.githubusercontent.com/49241737/69596662-4e8b7300-103e-11ea-9213-ca839d35be06.png)
我git下来，运行你的例子没问题，我把图片这些换成我的就不行了，求解答，谢谢作者
@songwsx

**Comment by songwsx** [comment]
需要注意下命名，可以看下我那个检索的小教程

**Comment by EtheneXiang** [comment]
请问一下，我需要怎么命名，需要什么格式

**Comment by songwsx** [comment]
![image](https://user-images.githubusercontent.com/32413719/69597418-e5f1c580-1040-11ea-99af-4a10287fae8a.png)
可以看我文章里面链接

**Comment by EtheneXiang** [comment]
that is soooooo greeeeeeeeeeeeeeet！！
谢谢，确实是命名的问题，我已经弄好了，可以查询自己的图片视频了。感谢你
