### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by chde222** [songwsx/person_search_demo#7]
您好，首先非常感谢您愿意分享您的代码
但是我在运行python search.py时报错，报错为No module named 'yacs'
我看了下代码在search.py，import语句中reid.config中确实没有cfg这个文件，在其他文件中也没有。请问一下这个文件在哪个位置。谢谢您了

**Comment by songwsx** [comment]
1. 没有这个模块你安装一下就好了 pip install yacs
2. 建议学一下python怎么导模块的，看看你主目录是不是当前目录

**Comment by chde222** [comment]
好的 我试试 谢谢您了

**Comment by songwsx** [comment]
> 好的 我试试 谢谢您了

试试在search.py最上面加上一行sys.path.append('.')
![image](https://user-images.githubusercontent.com/32413719/70311051-d8f88180-184b-11ea-84b1-7b71fda0ecbb.png)

**Comment by chde222** [comment]
嗯嗯 好的 谢谢

**Comment by chde222** [comment]
感谢 运行出来了 结果很不错
