### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Alexloveanna** [songwsx/person_search_demo#8]
ModuleNotFoundError: No module named 'reidCfg'我在运行search的时候报这个错误是什么原因啊

**Comment by songwsx** [comment]
[issue里面有](https://github.com/songwsx/person_search_demo/issues/7) 看看是不是当前目录问题

**Comment by Alexloveanna** [comment]
model = Darknet(cfg, img_size)
NameError: name 'Darknet' is not defined上一个问题解决了，，结果又来个问题，，麻烦松老师了
