### ISSUE TITLE
detect.py单独运行为什么不出结果？

### ISSUE THREAD

**Issue by ulanbator** [songwsx/person_search_demo#9]
你好，我放在服务器上当都运行detect.py代码为什么不显示检测结果？？但是search.py没问题！
![image](https://user-images.githubusercontent.com/26237152/70440086-60ecbe80-1acc-11ea-82f2-f463c50bf40b.png)
![Uploading image.png…]()

**Comment by songwsx** [comment]
检测结果在output文件夹

**Comment by ulanbator** [comment]
![image](https://user-images.githubusercontent.com/26237152/70441979-53d1ce80-1ad0-11ea-9f22-23bbbd0742aa.png)
![image](https://user-images.githubusercontent.com/26237152/70442004-62b88100-1ad0-11ea-9abd-c4e781952bdb.png)
这是控制台da'yi打印的信息，显示没有检测到,而且output只有原图并没有检测的结果

**Comment by songwsx** [comment]
模型配置文件和权重文件什么的检查看看

**Comment by ulanbator** [comment]
好的 谢谢了！

**Comment by songwsx** [comment]
更新了一下detect.py，给了默认配置，亲测可用

**Comment by ulanbator** [comment]
谢谢！
